bedutravels/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers
from graphene_django.views import GraphQLView

from profiles.views import UserViewSet
from tours.views import TourViewSet, ZoneViewSet
from tours.schema import schema

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'tours', TourViewSet)
router.register(r'zones', ZoneViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include('tours.urls')),
    path('profile/', include('profiles.urls', namespace='profile')),
    path('graphql', GraphQLView.as_view(graphiql=True, schema=schema)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

profiles/urls.py
from django.urls import path
from .views import (
    user_profile,
    login_user,
    logout_user,
    save_profile,
)

app_name = 'profiles'

urlpatterns = [
    path('login/', login_user, name='login_user'),
    path('logout/', logout_user, name='logout_user'),
    path('save-profile/', save_profile, name='save-profile'),
    path('', user_profile, name='index'),
]

tours/urls.py
from django.urls import path
from .views import (
    index,
)

urlpatterns = [
    path('', index, name='index'),
]

profiles/models.py
from django.db import models

# Create your models here.

tours/models.py
from uuid import uuid4
from django.db import models

GENDER = [
    ('M', 'Male'),
    ('F', 'Female'),
    ('O', 'Other'),
]


class User(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=80, null=True, blank=True)
    nickname = models.CharField(max_length=50, null=True, blank=True)
    email = models.EmailField()
    birthday = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER)
    key = models.CharField(max_length=50, null=True, blank=True)
    type = models.CharField(max_length=50, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} {self.last_name}'


class Zone(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    latitude = models.DecimalField(max_digits=8, decimal_places=6, null=True, blank=True)
    longitude = models.DecimalField(max_digits=8, decimal_places=6, null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


class Tour(models.Model):
    name = models.CharField(max_length=150)
    slug = models.SlugField()
    operator = models.CharField(max_length=50, null=True, blank=True)
    tour_type = models.CharField(max_length=50, null=True, blank=True)
    description = models.TextField()
    img = models.URLField()
    country = models.CharField(max_length=50, null=True, blank=True)
    takeoff_zone = models.ForeignKey(
        Zone,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='tours_takeoff'
    )
    arrival_zone = models.ForeignKey(
        Zone,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='tours_arrival'
    )

    def __str__(self):
        return f'{self.name}'

profiles/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse
from rest_framework import viewsets
from tours.models import User as tours_user
from profiles.serializers import TourUserSerializer
from utils import list2str

@login_required()
def user_profile(request):
    user_qs = User.objects.get(pk=request.user.pk)
    return render(
        request,
        'profiles/profile.html',
        {
            'user': user_qs,
        }
    )

@login_required()
def save_profile(request):
    if request.method == 'POST':
        form = {k: list2str(v) for k, v in request.POST.items()}
        form.pop('csrfmiddlewaretoken', None)
        form.pop('button', None)
        #tours_user.objects.create(**form)
        print(form)
    
    return redirect(reverse('profile:index'))

def login_user(request):
    
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        _next = request.GET.get('next', '/')
        access = authenticate(username=username, password=password)
        if access is not None:
            login(request, access)
            return redirect(_next)
        else:
            msg = 'Bad credentials!'
    else:
        msg = ''
    
    return render(
        request,
        'registration/login.html',
        {
            'msg': msg,
        }
    )

def logout_user(request):
    _next = request.GET.get('next', '/')
    logout(request)
    return redirect(_next)


class UserViewSet(viewsets.ModelViewSet):
    queryset = tours_user.objects.all().order_by('id')
    serializer_class = TourUserSerializer

tours/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from rest_framework import viewsets
from tours.models import Tour, Zone
from profiles.serializers import TourSerializer, ZoneSerializer

@login_required()
def index(request):
    tours = Tour.objects.all()
    return render(
        request,
        'tours/index.html',
        {
            'tours': tours,
            'tour_arrivals': tours.distinct().values_list('arrival_zone__name', flat=True),
            'tour_takeoff': tours.distinct().values_list('takeoff_zone__name', flat=True),
            'user': request.user,
        }
    )


class TourViewSet(viewsets.ModelViewSet):
    queryset = Tour.objects.all()
    serializer_class = TourSerializer


class ZoneViewSet(viewsets.ModelViewSet):
    queryset = Zone.objects.all()
    serializer_class = ZoneSerializer

templates/profiles/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Bedutravels - Perfil</title>
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
  <link rel="stylesheet" href="{% static 'css/destinos.css' %}">
  <link rel="stylesheet" href="{% static 'css/profile.css' %}">
</head>
<body>
  <nav class="menu_main">
      <a class="marca" href="#">
        <strong>BEDUTRAVELS</strong>
      </a>
      <div>
        {% if user.is_authenticated %}
          <a href="#">Bienvenido {{ user.username.capitalize }}</a>
          {% if user.is_superuser %}
          <a href="/admin/" target="_blank">Admin Panel</a>
          {% endif %}
          <a href="/logout/">Cerrar Sesion</a>
          {% else %}
          <a href="">LogIn</a>
          <a href="">SignIn</a>
          {% endif %}
      </div>
  </nav>

  <section class="profile-container padding-top-lg">
    <div>
      <div class="margin-bottom-sm">
        <p class="title-font margin-bottom-lg text-center">INFORMACIÓN DE TU CUENTA EN BEDUTRAVELS</p>
      </div>
      <div  class="profile-info">
        <form class="profile-inputs" action="{% url 'profile:save-profile' %}" method="POST">
           {% csrf_token %}
            Nombre: <input type="text" name="nombre" value="">
            Apellidos: <input type="text" name="apellidos" value="">
            Fecha de nacimiento: <input type="date" name="fechaNacimiento">
            Tipo: <input type="text" name="tipo" value="">
            <button class="button-tour margin-top-sm" style="align-self: center;" type="submit" name="button">
              Guardar infromación
            </button>
            <a href="" class="margin-top-md">Cambiar contraseña</a>
        </div>
        <div class="profile-img">
           <img class="margin-bottom-sm" src="{% static 'img/perfil_img.jpg' %}" alt="profile_image">
           <button class="button-tour " type="button" name="button">Cambiar foto de perfil</button>
        </div>
      </div>
    </div>

  </section>

  <footer class="margin-top-lg">
    <ul>
      <li>Bedu Travels</li>
      <li>hola@bedutravels.com</li>
    </ul>
    <div class="social-media-container">
      <img src="/static/perfiles/img/facebook.svg" alt="">
      <img src="/static/perfiles/img/twitter.svg" alt="">
      <img src="/static/perfiles/img/instagram.svg" alt="">
    </div>
  </footer>
</body>
</html>

templates/tours/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Bedu Travels</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/destinos.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  </head>
  <body>
    <nav class="menu_main">
        <a class="marca" href="#">
          <strong>BEDUTRAVELS</strong>
        </a>
        <div>
          {% if user.is_authenticated %}
          <a href="#">Bienvenido {{ user.username.capitalize }}</a>
          {% if user.is_superuser %}
          <a href="{% url 'admin:index' %}" target="_blank">Admin Panel</a>
          {% endif %}
          <a href="{% url 'profile:logout_user' %}">Cerrar Sesion</a>
          {% else %}
          <a href="{% url 'profile:login_user' %}">LogIn</a>
          <a href="">SignIn</a>
          {% endif %}
        </div>
    </nav>

    <section id="country-cover">
        <h2>Tours</h2>
        <h3>Destinos maravillosos para revitalizar el cuerpo y alimentar el alma</h3>
    </section>

    <section id="content">
      <aside id="column-left">
        <p class="margin-bottom-sm">Filtrar por:</p>
        <input class="margin-bottom-sm" type="text" name="" value="">
        <div class="margin-bottom-sm">
          <p>Destinos</p>
            <ul>
              {% for t in tour_arrivals %}
              <li>
                <input type="checkbox" id="fruit4" name="" value="">
                <label for="fruit4">{{ t }}</label>
              </li>
              {% endfor %}
           </ul>
         </div>
         <div class="margin-bottom-sm">
          <p>Salidas</p>
            <ul>
              {% for t in tour_takeoff %}
              <li>
                <input type="checkbox" id="fruit4" name="" value="">
                <label for="fruit4">{{ t }}</label>
              </li>
              {% endfor %}
           </ul>
         </div>
       </aside>

       <section id="central">
         {% for tour in tours %}
          <div class="tour-container">
            <div class="card-image-container">
              <img src="{{ tour.img }}" alt="{{ tour }}">
            </div>
            <div class="card-content">
              <div>
                <h3>{{ tour.name }}</h3>
                <p class="margin-bottom-sm">
                  {{ tour.description }}
                </p>

                <table class="table-info-tour">
                  <tbody>
                    <tr>
                      <th>Starts /Ends </th>
                      <td>{{ tour.takeoff_zone }}/{{ tour.arrival_zone }}</td>
                    </tr>
                    <tr>
                      <th>Operator</th>
                      <td>{{ tour.operator }}</td>
                    </tr>
                    <tr>
                      <th>Tour Type</th>
                      <td>{{ tour.tour_type }}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <div class="">
                <button class="button-tour">Ver tour</button>
              </div>
            </div>
          </div>
          {% endfor %}
        </section>
      </section>

      <footer class="margin-top-lg">
        <ul>
          <li>Bedu Travels</li>
          <li>hola@bedutravels.com</li>
        </ul>
        <div class="social-media-container">
          <img src="{% static 'img/facebook.svg' %}" alt="">
          <img src="{% static 'img/twitter.svg' %}" alt="">
          <img src="{% static 'img/instagram.svg' %}" alt="">
        </div>
      </footer>
  </body>

</html>